# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
#url: 
date_format: "ordinal"
title: Edward's personal blog
subtitle: "Edward's personal blog"
description: "Edward's personal blog"
keywords: Edward, personal, blog
timezone: Asia/Taipei
encoding: "utf-8"
side_bar_repo_limit: 5
repository: bluehomewu/edward.github.io
# 對 css 和 js 資源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 組件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子瀏覽統計
    busuanzi:
        enabled: true
        start_date: 2020-05-03
# 壓縮頁面內容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字數統計
word_count:
    enabled: true
# 高亮風格，支持的主題 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Edward Wu
organization: Havoc-OS, 就是愛刷機
organization_url: 
github_username: bluehomewu
location: Taipei, Taiwan
email: bluehome.wu@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首頁

  -
    href: /categories/
    label: 分類

#   -
#     href: /archives/
#     label: 歸檔

#   -
#     href: /open-source/
#     label: 開源

  -
    href: /wiki/
    label: wiki

  -
    href: /links/
    label: 鏈結

  -
    href: /about/
    label: 關於

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 請修改下方這些資訊為你自己申請的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: bluehomewu
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: bluehomewu
    repo: blog-comments
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用時其他評論套件時可點擊顯示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支援全文搜尋
    fulltext: false
    # 最多顯示多少搜尋結果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
